### ISSUE TITLE
どのようなWebシステムを作るか決める。

### ISSUE THREAD

**Issue by NakataTPD** [NakataTPD/2018-f-web-training#1]
### 前提
 - CRUD機能をもつこと。

WikiのHomeのシステム名と機能概要を修正してください。
※GithubのWikiはどのようなことを書くのか、どんな表現ができるのか、一般的な構成など、実際に公開されている他のパブリックリポジトリを覗いてみてください。

**Comment by FujiokaTPD** [comment]
RUNdays
日々のランニング距離、タイム、地図のデータ(Googleマップ)のデータを記録する。

**Comment by NakataTPD** [comment]
Wikiが更新されていませんので、再オープンします。

**Comment by NakataTPD** [comment]
> RUNdays
> 日々のランニング距離、タイム、地図のデータ(Googleマップ)のデータを記録する。

GoogleMapとの連携は、とりあえず動くものを作った後に機能拡張としてもいいですよ。
拡張する際に少しでも楽なようにインターフェースを意識しておくといいと思います。

**Comment by NakataTPD** [comment]
To : @FujiokaTPD 
以下、現Wikiの指摘です。
1."機能概要"と"普段のランニングの実績を記録するシステム"の体裁が同じですが、いいのですか？
2."拡張案"として考えられる機能を、新規で追加してください。
3.入力データですが、走った日付は不要ですか？
4.ちょっと入力データが少ない気がするので、体重（体脂肪とかもわかれば面白い？）とかも入力できるようにしてみては？(指摘というよりただの提案です。)

**Comment by NakataTPD** [comment]
To : @FujiokaTPD
以下、現Wikiの指摘です。
1."普段のランニングの実績を記録するシステム"はタイトルではないと思うので、句読点をつけましょう。あと、体裁もタイトル'###'にしないでください。
2.”機能”の内容ですが、１行目の”1日のランニングの実績を一つのレコードとして保存できる。”は登録機能だと思いますが、その他の行の機能名は何になりますか？２行目は一覧表示の中の１項目として理論値を表示する？３行目は集計画面を作る？ほかに、、更新機能、削除機能は？CRUDを含むことは、前提としています。

**Comment by FujiokaTPD** [comment]
機能概要内容「普段のランニングの実績を記録するシステム。」の修正を行いました。
同時に機能内容のNo.5の削除、No.6を機能拡張案の欄に移行しました。

**Comment by NakataTPD** [comment]
> 機能概要内容「普段のランニングの実績を記録するシステム。」の修正を行いました。
> 同時に機能内容のNo.5の削除、No.6を機能拡張案の欄に移行しました。

・機能概要内容がまだタイトルの見た目になってますので修正して下さい。
※機能概要内容の１行下（水平線の上）に改行を挿入するか、水平線の記法をハイフン以外にしてください。
・各行の末尾の不要な半角スペースは削除してください。

**Comment by FujiokaTPD** [comment]
機能概要内容を修正しました。
水平線は「＊＊＊」で記述しています。

**Comment by NakataTPD** [comment]
👍
