### ISSUE TITLE
画面構成を決める。

### ISSUE THREAD

**Issue by NakataTPD** [NakataTPD/2018-f-web-training#2]
作成する画面を決めて、画面一覧を作成してください。
マークダウンファイルで作成して下さい。
※マークダウンはdocumentの下に作成してください。
※ローカルマシンにSourceTreeをインストールして、developブランチから作成したfuture/createScreensListブランチをプッシュ＆プルリクしてください。

 - [x] SourceTreeのインストール
期間:新PCが届き次第対応
 - [x] 画面一覧作成
期間:12/5(水)~12/7(土)
 - [x] レビュー
期間:12/9(月)
 - [x] レビュー後修正
期間:12/9(月)~12/13(金)

**Comment by FujiokaTPD** [comment]
スケジュール
SourceTreeインストール：新PCが届き次第対応
画面一覧作成：12/5(水)～12/7(土)
自己レビュー：12/8(日)
レビュー：12/9(月) ～

**Comment by NakataTPD** [comment]
上記のコメントですが、このIssueの説明部を直接編集して記載して下さい。次からでもいいけど。

**Comment by FujiokaTPD** [comment]
画面一覧をWikiに記載しました。簡単な画面の説明も記載しています。
ご確認の程お願いします。

**Comment by NakataTPD** [comment]
1. 割り込みタスクを先に済ませて下さい。
2. WikiのHomeに作成するのではなく、画面一覧用のトピックを新規作成してそこに作成して下さい。あとでSourceTreeの環境が整ったときにまるっとdocument配下にxxx.mdとして移動できるように。
3. 画面一覧はマークダウンのテーブル記法で書いてください。
4. 画面遷移図も画面一覧内の別な章で記載して下さい。（やり方は任せます。エクセルやペイントで書いてスクショをマークダウンに貼ったりなど）
5. [重要]機能と画面の表記のずれを修正して下さい。（登録？入力？）（変更？編集？）

**Comment by NakataTPD** [comment]
1. 画面遷移図ですが、テーブル表記だと、表現できないことがでてくるので、別な表記にしてください。
2. 画面遷移図で、登録後、変更後、削除後はどこの画面に遷移するか表現して下さい。

**Comment by FujiokaTPD** [comment]
>5.[重要]機能と画面の表記のずれを修正して下さい。（登録？入力？）（変更？編集？）

  機能と画面名を統一しました。  
>1.画面遷移図ですが、テーブル表記だと、表現できないことがでてくるので、別な表記にしてください。  

  テーブル記法からExcelでの表記に変更しました。しかし、画面遷移図のスクショを張り付ける為のマークダウン記法がわかりません。ローカルにある画像ファイルを表示するにはどうすればよろしいでしょうか？
>2.画面遷移図で、登録後、変更後、削除後はどこの画面に遷移するか表現して下さい。  

  上記のExcelファイルに記載しています。

**Comment by FujiokaTPD** [comment]
画面構成の修正を行いました。確認の程お願いします。
Issueの成果物についての質問があります。
１．#7.環境構築の成果物は何か提示する物が必要でしょうか？それとも報告のみでしょうか？
２．#8.ベースプロジェクト作成の成果物はどのようなものでしょうか？

**Comment by NakataTPD** [comment]
> 画面構成の修正を行いました。確認の程お願いします。

確認しました 👍 
> Issueの成果物についての質問があります。
> １．#7.環境構築の成果物は何か提示する物が必要でしょうか？それとも報告のみでしょうか？

　　　→報告のみです。
> ２．#8.ベースプロジェクト作成の成果物はどのようなものでしょうか？

　　　→SpringBootのベースプロジェクトのプログラム一式になります。
　　　（ビルドが通り、SpringBootをGradle実行し、エラーなく起動すること）
