### ISSUE TITLE
画面イメージを考える。

### ISSUE THREAD

**Issue by NakataTPD** [NakataTPD/2018-f-web-training#3]
各画面イメージを作成してください。
方法はなんでもいいです。
※紙、Excel、Word、ペイント、HTML

 - [x] 画面イメージ作成
        期間:12/14(土)~12/15(日)
 - [x] レビュー
        期間:12/16(月)
 - [x] レビュー後修正
        期間:12/16(月)~12/20(金)

**Comment by FujiokaTPD** [comment]
画面イメージを作成しました。
WikiにExcelで作成したものと簡易の説明を載せています。
ご確認の程お願い致します。

**Comment by NakataTPD** [comment]
> 画面イメージを作成しました。
> WikiにExcelで作成したものと簡易の説明を載せています。
> ご確認の程お願い致します。

確認しました。
1. ホーム画面以外の画面ですが、データ１などではなく、具体的な項目とコントロールを考えて書いてみて下さい。
項目（日付、ランニング時間・・・）、コントロール（テキストボックス、カレンダー・・・）
2. 変更画面のボタンは、登録ではなく変更にしてください。
3. 一覧画面に変更ボタンと、削除ボタンがありますが、変更対象と削除対象のレコードはどのように選択する想定ですか？
4. 変更画面の説明に"一意制約違反になってしまうデータは表示のみで変更は不可とする。"とありますが、必要ですか？必要である場合、主キーの変更を許す仕様にする理由を教えて下さい。

**Comment by FujiokaTPD** [comment]
1. 指摘の修正を行いました。画面イメージを最新化しています。登録画面と変更画面に各項目の単位を表示するように記載しました。
2. ボタンの名称を修正を行いました。
3. 一覧には複数のレコードを表示し、クリックによって１レコードの選択ができるようにしたいと考えています。削除と変更の対象は一覧上で選択されているレコードを想定しています。
4. この説明は主キーに対しての変更が実行されることを防ぐ意図で記載しています。変更画面で主キーに変更を行った際、一意制約違反でエラーが発生することを未然に防ぐ為に、主キーのデータは入力枠は用意せず、登録されているデータを表示するのみで変更は実行できないようにしたいと考えています。登録されたレコードの主キーに対しての変更は画面上ではできないようにしたいと考えています。

**Comment by NakataTPD** [comment]
> * 一覧には複数のレコードを表示し、クリックによって１レコードの選択ができるようにしたいと考えています。削除と変更の対象は一覧上で選択されているレコードを想定しています。

はい。具体的な実装方法は把握できていますか？行選択は、JS＆CSSで可能ですが、たとえば行の中に削除リンクとか変更画面へのリンクを用意する実装に比べると少し難易度が高くなります。少しでも簡単に実装したいのであれば、行選択は拡張機能にまわしてもいいと思います。

> * この説明は主キーに対しての変更が実行されることを防ぐ意図で記載しています。変更画面で主キーに変更を行った際、一意制約違反でエラーが発生することを未然に防ぐ為に、主キーのデータは入力枠は用意せず、登録されているデータを表示するのみで変更は実行できないようにしたいと考えています。登録されたレコードの主キーに対しての変更は画面上ではできないようにしたいと考えています。

えっと、、日付がキーの想定ってことですね。それだと、登録画面でも一意制約のエラーがでる可能性がありますよね。あと、１日に１回しかランニングできないシステム起因の制約ができてしまいます。さらに、日付を間違えて登録した場合、１回削除して登録しなおす必要があり不便ですね。日付をキーにするのはやめましょう。

以下は追加
1. 各イメージの上部にあるコントロール説明？ですが、後で作成する画面項目一覧と内容がかぶるので、削除して下さい。（変更ボタンが登録ボタンのままになってたりしますし。。）

2. 各入力項目の入力チェックがエラーになった際に、どこにどのようにエラーメッセージを表示するのか、登録画面だけでよいので表現して下さい。（変更画面は、登録画面と同じと記載しておけばよいです。）

**Comment by FujiokaTPD** [comment]
>はい。具体的な実装方法は把握できていますか？行選択は、JS＆CSSで可能ですが、たとえば行の中に削除リンクとか変更画面へのリンクを用意する実装に比べると少し難易度が高くなります。少しでも簡単に実装したいのであれば、行選択は拡張機能にまわしてもいいと思います。  

一覧選択の機能は拡張機能としてWikiのHomeに追加します。JS＆CSSを使用した行選択機能については調べてWikiにまとめようと思います。
一覧に表示されているレコードを選択することで画面の遷移や削除処理実行を行います。変更画面への遷移と削除処理の実行を分ける方法が少し理解が曖昧なのですが、自分の元々の考えとして、変更ボタンと削除ボタンを押すことでフラグを立てることで、立っているフラグを基に処理を分けようと考えていました。

>えっと、、日付がキーの想定ってことですね。それだと、登録画面でも一意制約のエラーがでる可能性がありますよね。あと、１日に１回しかランニングできないシステム起因の制約ができてしまいます。さらに、日付を間違えて登録した場合、１回削除して登録しなおす必要があり不便ですね。日付をキーにするのはやめましょう。

画面に表示されるアイテムに主キーを設定しないこととする。新規登録時にシーケンスNo.を設定する。そのキーを基にランニング実績の変更なども行う。

1. Wikiにて修正を行います。
2. 画面イメージにてどのように表示するか案を出します。

**Comment by NakataTPD** [comment]
1. エラーメッセージですが、”入力データに誤りがあります。”では、何が誤っているかわからない曖昧なメッセージなので、具体的なメッセージを表示するようにしてください。（詳細設計で考えよう）画面イメージはイメージの表現のみでよいので、具体的なメッセージの記載はやめましょう。ｘｘｘなどの表現にしてください。

2. 「日付」の項目ですが、何の日付かわからないので、項目名を修正して下さい。「ランニング日」とか、「実施日」とか？

**Comment by FujiokaTPD** [comment]
1.  詳細設計で具体的なメッセージの表示を行うということで、画面イメージには[エラーメッセージ「×××」]と表記しています。
2.  日付は「ランニング日」で変更しています。
3. 一覧画面は行の中に削除処理実行のリンクと変更画面へのリンクを用意しています。あと、複数の実績が保存されると思うので、一度に表示できない実績データをページで分けて表示できるようにできないかと思いページ移動のボタンを追加しています。

**Comment by NakataTPD** [comment]
> 1. 詳細設計で具体的なメッセージの表示を行うということで、画面イメージには[エラーメッセージ「×××」]と表記しています。

変わっていないです。。

> 2. 日付は「ランニング日」で変更しています。

変わっていないです。。

> 3. 一覧画面は行の中に削除処理実行のリンクと変更画面へのリンクを用意しています。あと、複数の実績が保存されると思うので、一度に表示できない実績データをページで分けて表示できるようにできないかと思いページ移動のボタンを追加しています。

ページングは拡張機能としてもよいと思いますが、実装しますか？

**Comment by FujiokaTPD** [comment]
>> 1. 詳細設計で具体的なメッセージの表示を行うということで、画面イメージには[エラーメッセージ「×××」]と表記しています。

> 変わっていないです。。

変わりました！

>> 2. 日付は「ランニング日」で変更しています。

> 変わっていないです。。

変わりました！

> ページングは拡張機能としてもよいと思いますが、実装しますか？

とりあえず拡張機能としてHomeに記載します。また新しい機能を思い付いたら拡張機能に書いていこうと思います。

**Comment by NakataTPD** [comment]
> > > 1. 日付は「ランニング日」で変更しています。
> 
> > 変わっていないです。。
> 
> 変わりました！

登録画面と一覧画面の「日付」が「ランニング日」になっていません。。

**Comment by FujiokaTPD** [comment]
何度目かの正直です。。。

**Comment by NakataTPD** [comment]
> 何度目かの正直です。。。

指摘事項の修正は確認しました。
